#!/usr/bin/env ruby

require 'http'
require 'json'
require 'pry'
require 'ostruct'
require 'optparse'
require 'active_support/core_ext/string'


require_relative '../lib/gitlab'
require_relative '../lib/formatter'
require_relative '../lib/project'
require_relative '../lib/merge_request'
require_relative '../core_ext/string'



class User < OpenStruct
end


def list
  Gitlab.new do |g|
    reqs = g.merge_requests
    formatter.print_mrs(reqs)
  end
end

def browse(argv)
  mr_id = argv.shift.to_i
end

def formatter
  @formatter ||= Formatter.new(colors: use_colors?)
end

def use_colors?
  ARGV.find { |s| s == '--no-colors' }.nil?
end


$use_colors = use_colors?

case command = ARGV.first
when /b(rowse)?/
  browse(ARGV)
else # /l(ist)?/
  list
end
